import { yearSummary } from './timeline.js';

/**
 * Renders the timeline UI into a given container element.
 * @param {HTMLElement} container - The DOM element to render the timeline into.
 * @param {object} timeline - The timeline data object generated by buildTimeline().
 * @param {object} callbacks - An object containing callback functions.
 * @param {function(number): void} callbacks.onSelect - Callback invoked when a year is selected.
 * @returns {{setSelected: function(number): void}} An object with a setSelected function.
 */
export function renderTimeline(container, timeline, callbacks) {
  container.replaceChildren(); // Clear the container first

  const tlCaption = document.createElement('div');
  tlCaption.className = 'tl-caption';
  tlCaption.textContent = '（點選年份切換流年）'; // Initial hint text
  container.appendChild(tlCaption);

  const tlScroll = document.createElement('div');
  tlScroll.className = 'tl-scroll';
  container.appendChild(tlScroll);

  let currentBandDiv = null;
  let currentTlYearsDiv = null;
  let currentDecadalKey = null; // Used to group years by decadal (大限)

  timeline.years.forEach(entry => {
    // Generate a unique key for the current decadal or '童限'
    const decadalKey = entry.decadal
      ? `${entry.decadal.palaceIndex}-${entry.decadal.range[0]}-${entry.decadal.range[1]}`
      : 'null';

    if (decadalKey !== currentDecadalKey) {
      // Create a new band if the decadal changes
      currentDecadalKey = decadalKey;

      currentBandDiv = document.createElement('div');
      currentBandDiv.className = 'tl-band';
      tlScroll.appendChild(currentBandDiv);

      const bandLabel = document.createElement('div');
      bandLabel.className = 'tl-band-label';
      bandLabel.textContent = entry.decadal
        ? `${entry.decadal.range[0]}-${entry.decadal.range[1]} ${entry.decadal.palaceName}`
        : '童限';
      currentBandDiv.appendChild(bandLabel);

      currentTlYearsDiv = document.createElement('div');
      currentTlYearsDiv.className = 'tl-years';
      currentBandDiv.appendChild(currentTlYearsDiv);
    }

    // Create the individual year element
    const tlYear = document.createElement('div');
    tlYear.className = 'tl-year';
    tlYear.dataset.year = entry.year;
    tlYear.title = yearSummary(entry); // Tooltip text

    // Create dots for 'love' and 'note' flags
    const tlDots = document.createElement('div');
    tlDots.className = 'tl-dots';
    if (entry.flags.some(f => f.severity === 'love')) {
      const dot = document.createElement('span');
      dot.className = 'tl-dot love';
      tlDots.appendChild(dot);
    }
    if (entry.flags.some(f => f.severity === 'note')) {
      const dot = document.createElement('span');
      dot.className = 'tl-dot note';
      tlDots.appendChild(dot);
    }
    tlYear.appendChild(tlDots);

    // Create the score block with appropriate class for coloring
    const tlScore = document.createElement('div');
    tlScore.className = 'tl-score';
    if (entry.score <= -2) {
      tlScore.classList.add('tl-bad2');
    } else if (entry.score === -1) {
      tlScore.classList.add('tl-bad1');
    } else if (entry.score === 0) {
      tlScore.classList.add('tl-mid');
    } else if (entry.score >= 1) { // Catches good1 and love flags (score >= 1)
      tlScore.classList.add('tl-good');
    }
    tlYear.appendChild(tlScore);

    // Display last two digits of the year
    const tlY = document.createElement('span');
    tlY.className = 'tl-y';
    tlY.textContent = String(entry.year).slice(2);
    tlYear.appendChild(tlY);

    // Display nominal age (虛歲)
    const tlAge = document.createElement('span');
    tlAge.className = 'tl-age';
    tlAge.textContent = entry.xuSui;
    tlYear.appendChild(tlAge);

    currentTlYearsDiv.appendChild(tlYear);
  });

  // Legend: what the score bars and dots mean (users shouldn't have to ask)
  const legend = document.createElement('div');
  legend.className = 'tl-legend';
  const legendItems = [
    ['tl-score tl-good', '吉年（+1↑）'],
    ['tl-score tl-mid', '平（0）'],
    ['tl-score tl-bad1', '微凶（−1）'],
    ['tl-score tl-bad2', '凶（−2↓）'],
    ['tl-dot love', '桃花年（紅鸞／天喜坐流命）'],
    ['tl-dot note', '流命疊大限命'],
  ];
  legendItems.forEach(([cls, label]) => {
    const item = document.createElement('span');
    item.className = 'tl-legend-item';
    const swatch = document.createElement('span');
    swatch.className = `tl-legend-swatch ${cls}`;
    item.appendChild(swatch);
    item.appendChild(document.createTextNode(label));
    legend.appendChild(item);
  });
  const chipItem = document.createElement('span');
  chipItem.className = 'tl-legend-item';
  const chip = document.createElement('span');
  chip.className = 'ovlp-chip ovlp2';
  chip.textContent = '疊';
  chipItem.appendChild(chip);
  chipItem.appendChild(document.createTextNode('疊宮事件（盤面標記，懸停看詳情）'));
  legend.appendChild(chipItem);
  container.appendChild(legend);

  // Attach a single click listener to the scroll container for event delegation
  tlScroll.addEventListener('click', (event) => {
    const targetYearEl = event.target.closest('.tl-year');
    if (targetYearEl && callbacks.onSelect) {
      const year = Number(targetYearEl.dataset.year);
      callbacks.onSelect(year);
    }
  });

  /**
   * Selects a specific year in the timeline, updates the caption, and scrolls it into view.
   * @param {number} year - The year to be selected.
   */
  function setSelected(year) {
    // Remove 'tl-selected' class from any currently selected year
    const currentSelected = tlScroll.querySelector('.tl-year.tl-selected');
    if (currentSelected) {
      currentSelected.classList.remove('tl-selected');
    }

    // Add 'tl-selected' class to the new year element
    const newSelected = tlScroll.querySelector(`.tl-year[data-year="${year}"]`);
    if (newSelected) {
      newSelected.classList.add('tl-selected');

      // Update the caption with the summary of the selected year
      const entry = timeline.years.find(y => y.year === year);
      if (entry) {
        tlCaption.textContent = yearSummary(entry);
      } else {
        tlCaption.textContent = '（點選年份切換流年）'; // Fallback if year not found
      }

      // Scroll the timeline horizontally to center the selected year
      // Guard against potential undefined offsets in non-browser environments (e.g., JSDOM)
      if (newSelected.offsetLeft !== undefined && tlScroll.clientWidth !== undefined && newSelected.offsetWidth !== undefined) {
        const scrollLeft = newSelected.offsetLeft - tlScroll.clientWidth / 2 + newSelected.offsetWidth / 2;
        tlScroll.scrollLeft = Math.max(0, scrollLeft); // Ensure scrollLeft is not negative
      }
    } else {
      // If the target year element is not found, restore default caption
      tlCaption.textContent = '（點選年份切換流年）';
    }
  }

  return { setSelected };
}
